tmrowco/bloom-contrib

- transportation/rejsekort.js
- add better logging
- fix proper parsing of dates by detecting the date separator ("-" vs "/")
> Fix rejsekort

- .babelrc
- package.json
- playground/src/index.js
- yarn.lock
Instead of hardcoding each import, automatically import all integrations
> Auto import all integrations

- .circleci/config.yml
- .eslintrc
- .gitignore
- README.md
- integrations/transportation/tripit.js
- integrations/utils/loadenv.js
- integrations/utils/oauth.js
- package.json
- playground/integrationenv.js
- playground/src/index.html
- playground/src/index.js
- yarn.lock
- Added OAuth1.0a
- Added tripIt
> Add tripit and OAuth1.0a library

- integrations/electricity/linky.js
- package.json
- yarn.lock
Use [@bokub/linky](https://www.npmjs.com/package/@bokub/linky) module in linky integration.
Fixes #57
> Improve Linky integration

- co2eq/flights/README.md
- co2eq/flights/airports.json
> Fixed encoding of airports.json

- README.md
> Add Ryanair and automated Activity Tracking as integrations

- integrations/electricity/linky.js
- package.json
- yarn.lock
Reverts tmrowco/tmrowapp-contrib#95
> Revert "Improve Linky integration"

- co2eq/meal.js
- definitions.js
Based on https://github.com/tmrowco/tmrowapp/blob/fe2692256ce20a9bf1018169f60b68710a0af1c2/src/co2eq/meal.js
> Bring back model that calculates meal by type

- README.md
Minor typo fixes:
- "have any question" -> "have any questions"
- "integrations to" -> "integrations with"
> Grammar and typo fixes on README.md

- README.md
> Add missing yarn command in the readme file

- co2eq/meal.js
- co2eq/purchase/footprints.yml
- co2eq/purchase/index.js
- definitions.js
- Remove invalid icons
- Remove "Apple, " prefix
- Correct unit from 'g' to 'kg'
- Make sure to validate units
- Ability to calculate purchase footprint for units that are Liters, and Items
- Added UNIT constants in definitions
> Individual products

- co2eq/purchase/footprints.yml
Supersedes https://github.com/tmrowco/tmrowapp-contrib/pull/180
> (#68) Add GWP for 4 variants of ice cream from study

- co2eq/meal.js
- co2eq/purchase/index.js
- co2eq/transportation.js
I created a simple datastructure to enable us to write the carbon model explanations in the carbon models. Later on we might even make sure we read from the specific activity to generate it.
> Carbon model explanation

- co2eq/meal.js
- co2eq/purchase/footprints.yml
Should not be merged before tmrowco/tmrowapp#1047 is ready
> Added conversions to meals

- co2eq/meal.js
- co2eq/purchase/index.js
- co2eq/transportation.js
- package.json
- yarn.lock
It allows us to recalculate activities when footprints.yaml is updated.
Fixes tmrowco/tmrowapp#1048
> The modelVersion of carbon models now has a checksum of footprints.yaml if the model depend on it

- co2eq/purchase/footprints.yml
- definitions.js
Required in order to automatically detect and associate a phone with an entry of footprint.yml
> Add device id to phones

- co2eq/purchase/footprints.yml
FYI there is an extra level of depth that I know we can't use right now in the UI.
> Ademe smartphones

- co2eq/transportation.js
Thanks to Emmanuel Gentil.
Less extensive PR than what I want to do (with yml file) but that should fix issues using our current way of doing things.
> Updated transportation models

- co2eq/purchase/footprints.yml
Hi there, 
I added the servings for the fruits where it was missing. I used a food database you can find here: https://www.yazio.com/en/foods. It's pretty convinient. For some fruits I had to switch to the german database - there are more entries. 
Hope you like it, let me know if you want me to change anything.
> Add median servings for the rest of the fruits

- integrations/transportation/minvolkswagen.js
Sorry, but my last PR disappeared. I have implemented the changes that you requested. It now only fetches data since the last collect
> Added volkswagen integration

- co2eq/purchase/footprints.yml
fixes https://github.com/tmrowco/tmrowapp/issues/1250
> Update appliances icon

- co2eq/purchase/footprints.yml
fixes https://github.com/tmrowco/tmrowapp/issues/1285
> Peanut butter old key

- co2eq/car/index.js
Allows us to call this model from the app.
> Added carbonEmissions function to new car.js

- integrations/transportation/ryanair.js
> Fixes #303: Ryanair integration null token bug

- README.md
- co2eq/hotelpercountry.js
The number of people sharing a room is taken into account in the hotel model per country with the addition of a participants field in the lodging activity.
I have also added a participants field in the description of the transportation activity since it is used in the transportation.js model but wasn't present in the README.
> Improvement of hotel model with number of guests

- co2eq/transportation.js
- definitions.js
> added ebike as transportation mode

- co2eq/transportation.js
- definitions.js
fixes the biggest question of us all: what is walking's carbon footprint?
answer: look at the LCA of shoes!
> Added by foot

- co2eq/car/cars.json
- co2eq/car/index.js
- co2eq/transportation.js
Added source + more plausible estimate when no data is available
> Added Source of car factors and updated average factor

- playground/frontend/src/app.js
> Do not hardcode origin of playground server in client

- integrations/transportation/trainline.js
Fixes a regression from #361. Would have broken trainline...
> Fixes a regression in endDatetime change of trainline integration

- integrations/transportation/rejsekort.js
Fixes a silly bug introduced by #361 in the rejsekort integration. Fixes NORTHAPP-Y3
> Fixes a regression in the "Rejsekort" integration

- README.md
> Updated co2model description

- .circleci/config.yml
- .eslintrc
- .gitignore
- babel.config.js
- co2eq/purchase/footprints.yml
- co2eq/purchase/index.test.js
- definitions.js
- package.json
- yarn.lock
Fixes https://github.com/tmrowco/northapp-contrib/issues/368
Can't be merged right now the footprint.yml file is invalid and many tests as failing.
> Add tests to footprint.yml

- co2eq/purchase/index.js
- co2eq/utils.js
This is related to https://github.com/tmrowco/tmrow/pull/2029
> Adds a getChecksum() function in utils

- .circleci/config.yml
- .eslintrc
- .gitignore
- README.md
- co2eq/car/index.test.js
- co2eq/purchase/index.js
- co2eq/purchase/index.test.js
- integrations/electricity/linky.js
- integrations/loadEnv.js
- package.json
- playground/.eslintrc
- playground/frontend/src/app.js
- playground/frontend/src/components/icon.js
- playground/frontend/src/components/resultstable.js
- playground/yarn.lock
- yarn.lock
My first-time contribution here.  👋
I've worked on fixing an issue with the [Rejsekort integration](https://github.com/tmrowco/northapp-contrib/pull/396). While doing this, I came up with some suggestions around linting/Prettier setup (and ensuring it is enforced so we don't need [to manually format](https://github.com/tmrowco/northapp-contrib/pull/385)), lock files, postinstall step, Jest setup, and Playground behavior. 
As most of all of these adjustments are rather small, I hope that it makes sense as one PR. I'll happily remove commits if something is not useful for you or split this into smaller PRs.
Let me know if some of the commits require more explanation.
> Setup adjustments

- integrations/utils/oauth.js
Ref https://github.com/tmrowco/tmrow/issues/2986#issuecomment-637586135
> Add trailing slash redirect

- co2eq/transportation/index.js
@corradio Addressing the following issue: https://github.com/tmrowco/northapp-contrib/issues/407
> Add fallback for transportation times in case endDatetime is missing

- integrations/purchase/nordic-api-gateway.js
Forgot to push that correction of the signature of the collect function for the NAG integration
> Fix collect signature for NAG.

- co2eq/energy/index.js
Resolves https://github.com/tmrowco/tmrow/issues/3495
> Include mandatory field for district heating in modelCanRun

- co2eq/purchase/index.js
Forgot to bump the version after fixing the CPI conversion (#447 )
> Bump model version for purchases.

- integrations/purchase/bridge-api-categories.js
- integrations/purchase/nag-categories.js
Rookie mistake: the arrow function inside the map would not return a list of entries from which the object can be rebuilt. So it failed!
> Fix error in bank integrations category matching objects.

- co2eq/purchase/footprints.yml
https://github.com/tmrowco/bloom/issues/129
> Added synonyms

- integrations/purchase/bridge/bridge-api-categories.js
- integrations/purchase/nordic-api-gateway/nag-categories.js
Addresses parts of https://github.com/tmrowco/bloom/issues/119
> Add ignore categories for bank integrations.

- co2eq/purchase/index.js
@corradio for context, I forgot to bump the carbon model for the #486 PR
> Bump purchase carbon model.

- co2eq/flights/index.js
- co2eq/flights/index.test.js
#341
Updates **Flights** model to support roundtrips/return trips.
- Wrote additional tests to cover areas we weren't testing
- Changed model to handle return trips for distance + duration by multiplying footprint
- Changed model to handle return trips with airport codes by reversing and running calculations again (since the direction matters due to loadfactors, etc.)
> Support roundtrips in Flights model

- integrations/electricity/__tests__/energinet.test.js
- integrations/electricity/energinet.js
https://github.com/tmrowco/bloom/issues/408
Support multiple smart energinet meters.
> energinet: support multiple meters
