electricity/linky.js
electricity/renault-zoe.js
transportation/rejsekort.js

- Update to new specs by remove flag in config and adding a country code
- Zoé now creates one activity per charge (instead of one per each *hour* of charge)
- Use the Zoé user's profile's countrycode as a proxy for the car location

Zoé upgrade

---

playground/server.js

Instead of throwing the following error when running `yarn serve`, create an empty `env.json`.

Create env file if it doesn't exist

---

package.json
yarn.lock

Plugins mentioned in `babel-config.js` were not mentioned in package.json so doing `yarn` and `cd playground && yarn` was not installing these plugins so `yarn serve` was failing with module not found error
***Error:***
Added them to `package.json` of root directory.

Fix : missing babel dependecies added to package.json

---

integrations/transportation/ryanair.js
integrations/transportation/wizzair.js

A slight mistake on my part, it turns out awaiting `res.text()` was the way to go in error handling as it's connected to `HTTPError`'s super constructor :no_good: Without that, errors don't work properly. @FelixDQ , you were right 😂 I reverted the changes in both Wizzair and Ryanair

Fixed error handling

---

co2eq/meal.js

The original source (http://www.greeneatz.com/foods-carbon-footprint.html) did not include all of the foods listed in the source pdf and changed some of the names of the consumed foods. Luckily, they linked to the original source pdf, which I referenced when updating the list.
See #186 #189 #190 
@martincollignon

Update meal.js food list with more accurate source

---

co2eq/purchase/footprints.yml

Used Median Values from provided document, adding Conversion section just as the Apples example had. I added missing fruits/vegetables that were not in the list as well, left intensityKilograms and source properties as null for those items.
Did not include:
- Fruit Salad
- Dried fruit
- Canned Beans
- Sweet Corn
- Vegetable Dishes
- Soup
(Please let me know if I should include them with the changes.)

Updated fruits and vegetables in footprints.yml file

---

integrations/transportation/tfl.js

The first fix is to make sure the integration doesn't error out like in #260 . Secondly, we should be pulling through contactless data as well as oyster card data as that is a very popular way of paying for journeys. 
I need to pay for some journeys on my contactless card this week so I can see the data structure. Once I've done that, I'll ensure we loop through all Oyster and contactless cards on the account and aggregate all the journeys

Fix bug where no oyster cards present, add contactless

---

package.json
playground/frontend/src/app.js
playground/frontend/src/components/console.js
playground/frontend/src/components/consoleheader.js
playground/package.json
playground/yarn.lock

Uses [console-feed](https://github.com/samdenty/console-feed) for rendering of output and allows searching, filtering and ordering of output. Resolves #159 
TODO:

#159 Adds Console Component for rendering of output

---

integrations/transportation/tfl.js

update tfl request error message handling

---

co2eq/hotelpercountry.js
co2eq/lodging.js
co2eq/meal.js
co2eq/transportation.js

Problem it solves:
Also the titles are probably less relevant to users than the sources (publication) So: 
"Environmental impact of omnivorous, ovo-lacto-vegetarian, and vegan diet"
becomes
"Nature 2017"

replaced source lables with publication instead of title of the publication

---

playground/frontend/src/components/resultstable.js

Fix issue where some columns in results are not visible.
The `<ResultsTable />` has a `display: flex` that makes it not display properly if there's too much content - this fixes that by removing the `display: flex` and instead using the default `block`.

Updates ResultsTable to show all columns properly

---

co2eq/purchase/index.js

Bankin was creating activities with transportationMode: public_transport, alongside an amount spent.
We didn't have a carbon model able to work with this input, but we had one for spendings on trains, so I made sure we use that one instead.
cc @sorensvejstrup as this was one of the feedback I sent from the app, but no issue was created (yet).

Purchase model transport

---

playground/frontend/src/app.js
playground/frontend/src/components/consoleheader.js
playground/frontend/src/components/icon.js
playground/frontend/src/icons/arrow-down.svg
playground/frontend/src/icons/arrow-up.svg
playground/frontend/src/icons/clear.svg
playground/frontend/src/icons/double-arrow.svg
playground/package.json
playground/webpack.config.js
playground/yarn.lock

Fix issue where CircleCI fails because of a dependency in `playground`.
CircleCI is slowed down and fails half the times while trying to download the `@materials-ui/icons` package. 
As we're only using 4 icons from the package, I have copied the icons to assets and loaded them directly instead.

Remove dependency in "playground" that breaks CI

---

.circleci/config.yml
.gitignore
playground/package.json
playground/webpack.config.js
playground/yarn.lock

This reduces CI build time from ~10 min to ~20 seconds, and reduces size of `node_modules` from ~700mb to ~100mb.
The `"contrib": "../"` is what's causing crazy nesting - here's an example of what `yarn install` is doing:
`
Copying 
"/home/circleci/.cache/yarn/v2/npm-contrib-1.0.0-901f1bdc-87e0-4698-8936-6de2e1de626e-1582714616259/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/domain-browser/HISTORY.md" 
to
"/home/circleci/repo/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/contrib/playground/node_modules/domain-browser/HISTORY.md".
`

Fix dependency issue in "playground" that make CI slow

---

.eslintrc
package.json
yarn.lock

This PR fixes eslint extensions (I forgot the `prettier/react` plugin).
It also removes the `react/jsx-one-expression-per-line` rule, as it clashes with Prettier. Let me know if you think we need to keep it, as this is a bit more controversial.
Before:
```
<header className="App-header">
<h2>North App Playground</h2>
<p>
status:
{' '}
{connectionStatus}
</p>
<button type="button">
Link
{' '}
{icon}
</button>
</header>
```
After:
```
<header className="App-header">
<h2>North App Playground</h2>
<p>status: {connectionStatus}</p>
<button type="button">Link {icon}</button>
</header>
```

Updates ESLint extensions

---

README.md
co2eq/car/index.js
co2eq/flights/index.js
co2eq/hotelpercountry.js
co2eq/lodging.js
co2eq/transportation.js
co2eq/utils.js
integrations/electricity/barry.js
integrations/electricity/linky.js
integrations/electricity/orsted.js
integrations/electricity/renault-zoe.js
integrations/electricity/sense.js
integrations/electricity/tesla-cockpit.js
integrations/transportation/automatic.js
integrations/transportation/minvolkswagen.js
integrations/transportation/rejsekort.js
integrations/transportation/ryanair.js
integrations/transportation/tfl.js
integrations/transportation/trainline.js
integrations/transportation/tripit.js
integrations/transportation/uber.js
integrations/transportation/wizzair.js

Part of https://github.com/tmrowco/tmrow/issues/1932. This should replace all usages of `durationHours` with `endDatetime`. 
I disabled the `prettier` `formatOnSave` hook, as otherwise there would be too many unnecessary changes. But somehow the 2 files refactored in the commit 931fd9f are always automatically formatted...
Not sure how we should proceed with regards to testing?

Replaces "durationHours" with "endDatetime"

---

co2eq/flights/index.js

As title says, there shouldn't be a default export here - just a normal one.

Fixes a sneaky "default" that I missed during review

---

co2eq/hotelpercountry.js
co2eq/meal.js
co2eq/purchase/index.js
integrations/purchase/nordic-api-gateway.js
integrations/transportation/tripit.js

Part of https://github.com/tmrowco/tmrow/issues/1693. Since a purchase activity should also support multiple line entries (i.e. multiple products in one purchase), the decision was taken to combine this with the existing `ingredients` array type and create a generic `lineItems`.

Adds "lineItems" to replace "ingredients" and purchase type fields

---

integrations/transportation/__tests__/rejsekort.test.js
integrations/transportation/rejsekort.js
package.json

Fixes https://github.com/tmrowco/northapp-contrib/issues/395
Currently, the Rejsekort integration doesn't take into account users with multiple cards. As the code was rather inaccessible, I started by documenting most of the current behavior with a bunch of unit tests. 
The unit tests are done by mocking the `https` layer as this is used internally by `superagent`. One alternative was to mock `superagent` either using Jest (but turned out to be rather nasty due to the chained API) or using https://github.com/M6Web/superagent-mock (deemed too inflexible as we want the same route to return different responses).

Support multiple Rejsekort cards

---

co2eq/purchase/index.js
co2eq/purchase/index.test.js

The purchase model was failing with error "Missing consumer price index reference year" when applied to a purchase that wasn't monetary (such as 10 L of diesel).
The bug was fixed and a unit test was added.
FYI @pierresegonne

Fix CPI non monetary

---

co2eq/transportation/index.js

The new transportation model can now run even if a duration is not given.

Update modelCanRun of transportation

---

integrations/electricity/energinet.js

Resolves https://github.com/tmrowco/tmrow/issues/3483

Fix 23h for energinet and flat polyfill.

---

integrations/purchase/index.js

North imports all modules (or better: `*.js`) found in each the integrations folders in `contrib`. Since the `nag-categories.js` file is no source in itself, this breaks North. Added a quickfix but not sure if this may break Bloom?
Alternatively we just fix it in North, i.e. ignore the `Purchase` integrations (since they are not active anyway...)

Adds index.js to purchase integration folder to fix north compatibility

---

integrations/digital/outlook.js
integrations/electricity/barry.js
integrations/electricity/energinet.js
integrations/electricity/linky.js
integrations/electricity/orsted.js
integrations/electricity/renault-zoe.js
integrations/electricity/sense.js
integrations/electricity/tesla-cockpit.js
integrations/purchase/nordic-api-gateway.js
integrations/transportation/automatic.js
integrations/transportation/minvolkswagen.js
integrations/transportation/rejsekort.js
integrations/transportation/ryanair.js
integrations/transportation/tfl.js
integrations/transportation/trainline.js
integrations/transportation/tripit.js
integrations/transportation/uber.js
integrations/transportation/wizzair.js

This PR adds an `id` field to the config object of all integrations. 
This will make it easier to have a unique, URL-friendly name for all integrations.

Adds id to all integrations

---

co2eq/purchase/index.js
co2eq/purchase/index.test.js

Looking at the CO2e transparency flow, I realised the massive mistake I did in the past when implementing the CPI conversion.
The conversion used to be done with 
```
const eurAmountAdjusted = eurAmount * (CPIcurrent / CPIreference);
```
where `CPIcurrent` refers to the CPI for the year of the datetime of the activity and `CPIreference` to the CPI for the year of the reference year (2011 for EXIOBASE data). It should be instead:
```
const eurAmountAdjusted = eurAmount * (CPIreference / CPIcurrent);
```
To show why, imagine 10€ in 2020€ spent in DE. The CPI for 2011 is 95.2, the CPI for 2020 is 105.5. With the old model, the adjusted price would thus be 10 * (105.5 / 95.2) = 11.08€. With the new model it becomes 10 * (95.2 / 105.5) = 9.02€.
To check, think about old prices re-adjusted for …

Fix co2eq cpi conversion.

---

integrations/electricity/energinet.js

We want to ensure that the input-token has a name that is not tied up to a specific function (fx access-token or refresh-token), but rather be more agnostic about how it's used by an integration.
This will make it possible to align this value everywhere and thus easier to use :)

Renames token variable name in state

---

co2eq/purchase/footprints.yml

avocado's are classified as fruits, but it was in vegetables so I moved it to fruits.

Moved avocado from vegetable to fruit

---

integrations/authentication/OAuth2Manager.js

The presence of the scope parameter made the Linky integration fail.
Fix is tested on North in simulator. cc @sorensvejstrup

Fix OAuth for Linky

---

integrations/electricity/energinet.js

Instead of fetching the last 5 days, integration now remembers last successfully date fetched and starts from there.
This should guarantee that we have no holes in the data.
Also added some logs.
ref https://github.com/tmrowco/bloom/issues/26

Better energinet

---

co2eq/purchase/index.js

Resolves #465
Changes the Purchases `modelCanRun` function to check for `identifier` in `lineItems`. 
This change will mean the co2engine package will throw many more `'No carbonModel available for this activity.'` errors. I don't think it has any implications, but would love some additional thoughts here :)

Adds check for identifier

---

co2eq/purchase/footprints.yml

"Housing" and "Information & com'" didn't have any icons, as can be seen here:
I therefore added the home and laptop icons.

Added home and laptop icons

---

integrations/loadEnv.js

Skip loading the env.json file, which we no longer use. Instead of removing the `loadEnv` completely, I updated it to use `process.env`.
Note that this is a blocker for migrating to TypeScript.

Skip loading env.json file

---

.circleci/config.yml
.eslintignore
.gitignore
README.md
co2eq/flights/airports.js
co2eq/flights/index.js
co2eq/food/ingredients.js
co2eq/purchase/README.md
co2eq/purchase/exiobase/prepare.py
co2eq/purchase/footprints.js
co2eq/purchase/footprints.yml
co2eq/purchase/index.js
package.json
playground/frontend/src/components/console.js
playground/frontend/src/components/consoleheader.js
playground/package.json
scripts/build.sh
scripts/release.sh
yarn.lock

Setup of build step and auto-publishing of bloom-contrib to npm.
While doing this I also updated all the references to the old northapp repository.
I tested this [locally](https://www.npmjs.com/package/@tmrow/bloom-contrib) and tried to set the right SSH key for GitHub pushes + npm token on CircleCI.
More context: https://github.com/tmrowco/bloom/pull/199#issuecomment-725263384 https://github.com/tmrowco/bloom/issues/217

Publish bloom-contrib as an npm package

---

.circleci/config.yml
yarn.lock

https://github.com/tmrowco/bloom-contrib/pull/481 failed after merging as the yarn lock file was not updated. This doesn't fail locally, like due to another version of yarn.

Update lock files to fix deployment

---

.circleci/config.yml

We are getting closer to releasing the package! 
Follow up on https://github.com/tmrowco/bloom-contrib/pull/482
https://support.circleci.com/hc/en-us/articles/360018860473-How-to-push-a-commit-back-to-the-same-repository-as-part-of-the-CircleCI-job

CI: Configure git user before releasing

---

.circleci/config.yml
.github/workflows/deploy.yml
.github/workflows/verify.yml
package.json

CircleCI is failing to verify GitHub's SSH key... This seems like a [known](https://discuss.circleci.com/t/the-authenticity-of-github-host-cant-be-stablished/33133) [problem](https://discuss.circleci.com/t/git-clone-fails-in-circle-2-0/15211) when trying to push to GitHub from CircleCI. I guess the SSH key should be updated?
Instead of spending more time on this, I suggest just using GitHub actions. It seems like a stable solution – and I've successfully used it for publishing packages in a [few](https://github.com/bash-lsp/bash-language-server) projects.

Setup GitHub workflows instead of CircleCI

---

README.md
co2eq/food/meal.js
co2eq/food/meal.test.js

https://github.com/tmrowco/bloom/issues/338
Updates **Meal** model to support multiplying the emission by number of meals/participants.
- Wrote tests to cover existing model
- Added new functionality
- Bumped model version
I am not sure about best approach here with regards to name - I have here reused `participants` from `transportation`, but would it make more sense to have something like "numberOfMeals" instead? 🤔 
I'm unsure if it's too weird that `participants` is **multiplying** emissions here, but **dividing** emissions in the transportation model.

Supports multiplying by number of participants in meal model

---

co2eq/food/ingredients.js

https://github.com/tmrowco/bloom/issues/404
Adjust `modelCanRun` for ingredients model to not be as greedy. 
To me this shows that we need a better way of annotating the supported types and how to not duplicate `modelCanRun` and the validation done in the model. 
I suggest we investigate https://github.com/colinhacks/zod or https://github.com/pelotom/runtypes

Less greedy modelCanRun for ingredients model
